# LOAD PACKAGES
#devtools::install_github('Blue-Matter/openMSE')
library(openMSE)
library(tidyverse)
library(purrr)
library(reshape2)
library(ggplot2)
library(ggsci)
library(viridis)
library(RColorBrewer)
library(colorBlindness)
library(cowplot)
library(future)
library(ggmse)
library(rosettafish)
#library(gfiscamutils)
library(gfplot)
library(ggmse)
#library(MASS) # this will stop dplyr::select working

